name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - pipeline
  pull_request:
    branches:
      - main
      - pipeline

jobs:
  frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22
          cache: 'npm'
          cache-dependency-path: 'frontend/package-lock.json'  # Correct path to package-lock.json

      - name: Debug Show Directory Structure
        run: ls -la

      - name: Debug Show Contents of Frontend Folder
        run: ls -la frontend

      - name: Install Dependencies
        run: npm ci
        working-directory: frontend
