name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend  # Ensures commands are executed inside frontend/

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Debug Files (Check if package-lock.json exists)
        run: ls -la
        working-directory: frontend

      - name: Install Dependencies
        run: npm ci  # Uses package-lock.json for clean install